services: 
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - 6379:6379
    
    db:
        image: postgres
        container_name: db
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=123
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
    
    api:
        build: ./UnoTrip.Backend
        container_name: api
        restart: always
        ports:
            - 443:443
        environment:
            - CONNECTION_STRING=Host=0.0.0.0;Port=5432;Database=postgres;Username=postgres;Password=123;
        depends_on:
            db:
                condition: service_healthy
    
    bot:
        build: ./UnoTrip.Bot
        container_name: client
        restart: always
        depends_on: 
            - redis
            - api