services: 
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - 6379:6379
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    
    db:
        image: postgres
        container_name: db
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=123
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
    
    api:
        build: ./UnoTrip.Backend
        container_name: api
        restart: always
        ports:
            - 8080:8080
        depends_on:
            db:
                condition: service_healthy
    
    bot:
        build: ./UnoTrip.Bot
        container_name: bot
        restart: always
        environment:
            - API_HOST=http://api:8080
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on: 
            - redis
            - api