services: 
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - 6379:6379
    
    db:
        image: postgres
        container_name: db
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=123
    
    api:
        build: ./UnoTrip.Api
        container_name: api
        restart: always
        ports:
            - 5174:5174
        depends_on:
            db:
                condition: service_healthy
    
    bot:
        build: ./UnoTrip.Bot
        container_name: client
        restart: always
        depends_on: 
            - redis
            - api